"""
Probability-map generation for the SPICSCON 2026 indoor positioning simulation.

This module converts signal measurements into location probability maps over the
10 x 10 indoor grid.

For each time step:
- WiFi measurement -> WiFi likelihood over 100 grid cells
- VLP measurement  -> VLP likelihood over 100 grid cells
- static fusion    -> weighted WiFi/VLP probability map

These probability maps are the foundation for:
- WiFi-only localization
- VLP-only localization
- static fusion
- DSP-based fusion
- graph smoothing
- adaptive fusion
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Mapping, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.environment import create_anchors
from src.signal_models import expected_vlp_intensity, expected_wifi_rssi
from src.utils import ensure_dir, load_config, save_csv, save_json


def load_grid_cells(path: str | Path = "results/raw/grid_cells.csv") -> pd.DataFrame:
    """
    Load grid-cell center coordinates generated by src.environment.

    Returns
    -------
    pandas.DataFrame
        Columns: cell_id, row, col, x, y
    """
    path = Path(path)

    if not path.exists():
        raise FileNotFoundError(
            f"Missing grid-cell file: {path}. "
            "Run: python -m src.environment --config configs/default.yaml --seed 101"
        )

    return pd.read_csv(path)


def grid_xy(cells: pd.DataFrame) -> np.ndarray:
    """
    Return grid-cell center coordinates as an array of shape (num_cells, 2).
    """
    return cells[["x", "y"]].to_numpy(dtype=float)


def softmax_log_probs(log_probs: np.ndarray, prob_floor: float = 1e-12) -> np.ndarray:
    """
    Numerically stable softmax for log-probability scores.

    A tiny probability floor is applied after softmax. This avoids exact zero
    probabilities caused by numerical underflow. That is useful later for
    entropy/confidence calculations and graph smoothing.

    Parameters
    ----------
    log_probs:
        Array of unnormalized log probabilities.
    prob_floor:
        Minimum probability assigned to each grid cell before renormalization.

    Returns
    -------
    np.ndarray
        Normalized probability vector that sums to 1.
    """
    log_probs = np.asarray(log_probs, dtype=float)
    shifted = log_probs - np.max(log_probs)
    exp_values = np.exp(shifted)
    total = np.sum(exp_values)

    if not np.isfinite(total) or total <= 0:
        prob = np.ones_like(log_probs) / len(log_probs)
    else:
        prob = exp_values / total

    prob = np.clip(prob, a_min=prob_floor, a_max=None)
    prob = prob / np.sum(prob)

    return prob


def normalize_prob(prob: np.ndarray) -> np.ndarray:
    """
    Normalize a probability vector safely.
    """
    prob = np.asarray(prob, dtype=float)
    prob = np.clip(prob, a_min=0.0, a_max=None)
    total = np.sum(prob)

    if not np.isfinite(total) or total <= 0:
        return np.ones_like(prob) / len(prob)

    return prob / total


def gaussian_log_likelihood(
    measured: np.ndarray,
    expected: np.ndarray,
    sigma: float | np.ndarray,
) -> np.ndarray:
    """
    Compute Gaussian log-likelihood for all candidate cells.

    Parameters
    ----------
    measured:
        Measurement vector of shape (num_anchors,).
    expected:
        Expected signal matrix of shape (num_cells, num_anchors).
    sigma:
        Noise standard deviation. Can be scalar or anchor-wise vector.

    Returns
    -------
    np.ndarray
        Log-likelihood score for each grid cell, shape (num_cells,).
    """
    measured = np.asarray(measured, dtype=float)
    expected = np.asarray(expected, dtype=float)
    sigma = np.asarray(sigma, dtype=float)

    sigma = np.maximum(sigma, 1e-9)

    residual = expected - measured[None, :]
    z = residual / sigma

    # Constants are included for completeness, but they do not affect argmax.
    log_term = np.log(2.0 * np.pi * sigma**2)
    log_like = -0.5 * np.sum(z**2 + log_term, axis=1)

    return log_like


def wifi_measurement_from_row(row: pd.Series) -> np.ndarray:
    """
    Extract measured WiFi RSSI vector from one signal row.
    """
    cols = ["wifi_ap1_dbm", "wifi_ap2_dbm", "wifi_ap3_dbm"]
    return row[cols].to_numpy(dtype=float)


def vlp_measurement_from_row(row: pd.Series) -> np.ndarray:
    """
    Extract measured VLP intensity vector from one signal row.
    """
    cols = [
        "vlp_led1_intensity",
        "vlp_led2_intensity",
        "vlp_led3_intensity",
        "vlp_led4_intensity",
    ]
    return row[cols].to_numpy(dtype=float)


def wifi_probability_map(
    cfg: Mapping,
    cells: pd.DataFrame,
    row: pd.Series,
) -> np.ndarray:
    """
    Convert one WiFi measurement row into a 100-cell probability map.

    For localization, we intentionally do not use the true position. We compare
    measured RSSI against expected RSSI at each candidate grid cell.
    """
    anchors = create_anchors(cfg)
    points_xy = grid_xy(cells)

    wifi_cfg = cfg["wifi_model"]

    expected = expected_wifi_rssi(
        points_xy=points_xy,
        wifi_ap_xy=anchors["wifi_ap"],
        p0_dbm=float(wifi_cfg["p0_dbm"]),
        path_loss_n=float(wifi_cfg["path_loss_n"]),
    )

    measured = wifi_measurement_from_row(row)

    # Use base sigma for likelihood. Degraded measurements should naturally fit worse.
    sigma = float(wifi_cfg["base_sigma_db"])

    log_like = gaussian_log_likelihood(measured=measured, expected=expected, sigma=sigma)
    return softmax_log_probs(log_like)


def vlp_probability_map(
    cfg: Mapping,
    cells: pd.DataFrame,
    row: pd.Series,
) -> np.ndarray:
    """
    Convert one VLP measurement row into a 100-cell probability map.

    We use the clean expected optical model. If VLP is blocked, the measured
    intensity may mismatch the model and therefore localization can degrade.
    """
    anchors = create_anchors(cfg)
    points_xy = grid_xy(cells)

    vlp_cfg = cfg["vlp_model"]

    expected = expected_vlp_intensity(
        points_xy=points_xy,
        led_xy=anchors["leds"],
        led_power=float(vlp_cfg["led_power"]),
        receiver_height_m=float(vlp_cfg["receiver_height_m"]),
        ceiling_height_m=float(vlp_cfg["ceiling_height_m"]),
    )

    measured = vlp_measurement_from_row(row)

    typical_scale = max(float(np.mean(expected)), 1e-9)
    sigma = float(vlp_cfg["base_sigma"]) * typical_scale

    log_like = gaussian_log_likelihood(measured=measured, expected=expected, sigma=sigma)
    return softmax_log_probs(log_like)


def fuse_probability_maps(
    p_wifi: np.ndarray,
    p_vlp: np.ndarray,
    wifi_weight: float = 0.5,
) -> np.ndarray:
    """
    Static weighted fusion of WiFi and VLP probability maps.
    """
    wifi_weight = float(wifi_weight)
    wifi_weight = float(np.clip(wifi_weight, 0.0, 1.0))

    fused = wifi_weight * normalize_prob(p_wifi) + (1.0 - wifi_weight) * normalize_prob(p_vlp)
    return normalize_prob(fused)


def estimate_position(
    prob: np.ndarray,
    cells: pd.DataFrame,
    method: str = "argmax",
) -> Dict[str, float]:
    """
    Estimate position from a probability map.

    method='argmax':
        Choose the highest-probability grid cell.

    method='expected':
        Compute the probability-weighted coordinate average.
    """
    prob = normalize_prob(prob)

    if method == "argmax":
        idx = int(np.argmax(prob))
        selected = cells.iloc[idx]
        return {
            "cell_id": int(selected["cell_id"]),
            "x": float(selected["x"]),
            "y": float(selected["y"]),
            "max_prob": float(prob[idx]),
        }

    if method == "expected":
        x = float(np.sum(prob * cells["x"].to_numpy(dtype=float)))
        y = float(np.sum(prob * cells["y"].to_numpy(dtype=float)))
        idx = int(np.argmax(prob))
        selected = cells.iloc[idx]
        return {
            "cell_id": int(selected["cell_id"]),
            "x": x,
            "y": y,
            "max_prob": float(prob[idx]),
        }

    raise ValueError("method must be either 'argmax' or 'expected'.")


def make_probability_table(
    cfg: Mapping,
    cells: pd.DataFrame,
    signal_row: pd.Series,
    wifi_weight: float = 0.5,
) -> pd.DataFrame:
    """
    Create a probability table for one signal time step.

    Returns
    -------
    pandas.DataFrame
        Grid-cell table with p_wifi, p_vlp, and p_static columns.
    """
    p_wifi = wifi_probability_map(cfg=cfg, cells=cells, row=signal_row)
    p_vlp = vlp_probability_map(cfg=cfg, cells=cells, row=signal_row)
    p_static = fuse_probability_maps(p_wifi=p_wifi, p_vlp=p_vlp, wifi_weight=wifi_weight)

    table = cells.copy()
    table["p_wifi"] = p_wifi
    table["p_vlp"] = p_vlp
    table["p_static"] = p_static

    return table


def probability_to_grid(
    prob: np.ndarray,
    cells: pd.DataFrame,
    grid_size: int,
) -> np.ndarray:
    """
    Convert a flat probability vector into a grid-shaped 2D array.
    """
    grid = np.zeros((grid_size, grid_size), dtype=float)

    for value, (_, row) in zip(prob, cells.iterrows()):
        r = int(row["row"])
        c = int(row["col"])
        grid[r, c] = value

    return grid


def plot_probability_sanity(
    prob_table: pd.DataFrame,
    cfg: Mapping,
    signal_row: pd.Series,
    output_path: str | Path = "results/figures/fig_probability_map_sanity.png",
) -> Path:
    """
    Plot WiFi, VLP, and static-fusion probability maps for one time step.
    """
    output_path = Path(output_path)
    ensure_dir(output_path.parent)

    grid_size = int(cfg["room"]["grid_size"])

    maps = {
        "WiFi probability": prob_table["p_wifi"].to_numpy(dtype=float),
        "VLP probability": prob_table["p_vlp"].to_numpy(dtype=float),
        "Static fusion probability": prob_table["p_static"].to_numpy(dtype=float),
    }

    fig, axes = plt.subplots(1, 3, figsize=(12.0, 3.8), constrained_layout=True)

    true_x = float(signal_row["true_x"])
    true_y = float(signal_row["true_y"])

    for ax, (title, prob) in zip(axes, maps.items()):
        grid_prob = probability_to_grid(prob, prob_table, grid_size=grid_size)

        im = ax.imshow(
            grid_prob,
            origin="lower",
            extent=[0, cfg["room"]["width_m"], 0, cfg["room"]["height_m"]],
            aspect="equal",
        )

        ax.scatter(true_x, true_y, marker="x", s=80, label="True position")
        ax.set_title(title)
        ax.set_xlabel("x (m)")
        ax.set_ylabel("y (m)")
        ax.legend(fontsize=7)
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

    fig.suptitle(
        f"Probability Map Sanity Check: {signal_row['scenario']} at t={int(signal_row['t'])}",
        fontsize=12,
    )

    fig.savefig(output_path, dpi=300)
    plt.close(fig)

    return output_path


def choose_sample_time(signal_df: pd.DataFrame, scenario: str) -> int:
    """
    Choose a useful sample time step for plotting.

    For degraded scenarios, choose the first degraded/blocked time step.
    Otherwise choose the middle time step.
    """
    scenario = scenario.lower()

    if scenario == "s2_wifi_degraded":
        idx = signal_df.index[signal_df["wifi_degraded"] == True].tolist()
        if idx:
            return int(signal_df.loc[idx[0], "t"])

    if scenario == "s3_vlp_blocked":
        idx = signal_df.index[signal_df["vlp_blocked"] == True].tolist()
        if idx:
            return int(signal_df.loc[idx[0], "t"])

    if scenario == "s4_mixed_dynamic":
        idx = signal_df.index[
            (signal_df["wifi_degraded"] == True) | (signal_df["vlp_blocked"] == True)
        ].tolist()
        if idx:
            return int(signal_df.loc[idx[0], "t"])

    return int(signal_df["t"].iloc[len(signal_df) // 2])


def build_probability_outputs(
    config_path: str | Path = "configs/default.yaml",
    seed: int = 101,
    scenario: str = "s2_wifi_degraded",
    time_step: int | None = None,
) -> Dict[str, str]:
    """
    Build one sample probability-map table and figure for sanity checking.
    """
    cfg = load_config(config_path)
    cells = load_grid_cells("results/raw/grid_cells.csv")

    signal_path = Path(f"results/raw/signals_seed{seed}_{scenario}.csv")
    if not signal_path.exists():
        raise FileNotFoundError(
            f"Missing signal file: {signal_path}. "
            f"Run: python -m src.signal_models --config {config_path} --seed {seed}"
        )

    signal_df = pd.read_csv(signal_path)

    if time_step is None:
        time_step = choose_sample_time(signal_df, scenario=scenario)

    selected = signal_df[signal_df["t"] == int(time_step)]
    if selected.empty:
        raise ValueError(f"time_step={time_step} not found in {signal_path}")

    signal_row = selected.iloc[0]

    prob_table = make_probability_table(
        cfg=cfg,
        cells=cells,
        signal_row=signal_row,
        wifi_weight=0.5,
    )

    output_csv = f"results/processed/probability_sample_seed{seed}_{scenario}_t{int(time_step)}.csv"
    save_csv(prob_table, output_csv)

    figure_path = plot_probability_sanity(
        prob_table=prob_table,
        cfg=cfg,
        signal_row=signal_row,
        output_path="results/figures/fig_probability_map_sanity.png",
    )

    p_wifi = prob_table["p_wifi"].to_numpy(dtype=float)
    p_vlp = prob_table["p_vlp"].to_numpy(dtype=float)
    p_static = prob_table["p_static"].to_numpy(dtype=float)

    wifi_est = estimate_position(p_wifi, cells, method="argmax")
    vlp_est = estimate_position(p_vlp, cells, method="argmax")
    static_est = estimate_position(p_static, cells, method="argmax")

    summary = {
        "seed": seed,
        "scenario": scenario,
        "time_step": int(time_step),
        "true_position": {
            "x": float(signal_row["true_x"]),
            "y": float(signal_row["true_y"]),
        },
        "wifi_estimate": wifi_est,
        "vlp_estimate": vlp_est,
        "static_fusion_estimate": static_est,
        "outputs": {
            "probability_sample_csv": output_csv,
            "probability_sanity_figure": str(figure_path),
        },
    }

    summary_path = "results/logs/probability_map_summary.json"
    save_json(summary, summary_path)

    return {
        "probability_sample_csv": output_csv,
        "probability_sanity_figure": str(figure_path),
        "probability_map_summary": summary_path,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create WiFi/VLP/static-fusion probability maps over grid cells."
    )
    parser.add_argument(
        "--config",
        type=str,
        default="configs/default.yaml",
        help="Path to YAML config file.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=101,
        help="Seed matching generated signals.",
    )
    parser.add_argument(
        "--scenario",
        type=str,
        default="s2_wifi_degraded",
        choices=["s1_clean", "s2_wifi_degraded", "s3_vlp_blocked", "s4_mixed_dynamic"],
        help="Scenario to use for probability-map sanity check.",
    )
    parser.add_argument(
        "--time-step",
        type=int,
        default=None,
        help="Optional time step for sanity plot. If omitted, a useful time step is chosen automatically.",
    )

    args = parser.parse_args()

    outputs = build_probability_outputs(
        config_path=args.config,
        seed=args.seed,
        scenario=args.scenario,
        time_step=args.time_step,
    )

    print("PROBABILITY MAP TEST OK")
    for name, path in outputs.items():
        print(f"{name}: {path}")


if __name__ == "__main__":
    main()
